In [2]:
import torch


111


In [3]:
x = torch.arange(12)
x

C:\Users\Jeff\AppData\Local\Temp\ipykernel_15812\3360310955.py:1: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  x = torch.arange(12)


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
x.shape


torch.Size([12])

In [7]:
x.numel() 

12

In [10]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
x = torch.ones((2,3,4))
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [18]:
x = torch.tensor([[[1,2,3],[1,2,3]]])

x

tensor([[[1, 2, 3],
         [1, 2, 3]]])

In [20]:
x = torch.tensor([1.0,2,4,8])
x
y = torch.tensor([2,2,2,2])
y
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [25]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [29]:
x == y
x.sum()

tensor(66.)

In [31]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)

a,b,a+b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [32]:
x[-1],x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [33]:
before = id(y)
y = y+x
id(y)==before

False

In [34]:
z = torch.zeros_like(y)

print(id(z))

z[:]=x +y

print(z)

1712731674304
tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])


In [40]:
# import os
# from mxnet import sys
# a = sym.var()
# b = sym.var()
# c=2*a+b 


ModuleNotFoundError: No module named 'mxnet'

In [46]:
import torch 
x = torch.arange(4.0)
x

x.requires_grad_(True)
x.grad


y = 2 * torch.dot(x,x)
y.backward()

x.grad == 4*x

tensor([True, True, True, True])

In [50]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
x.grad==u

tensor([True, True, True, True])

In [52]:
def f(a):
    b =a *2 
    while b.norm() <1000:
        b =b *2
    if b.sum() >0:
         c= b
    else :
        c =100*b
    return c
a = torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()
a.grad == d/a,a


(tensor(True), tensor(1.1380, requires_grad=True))

In [63]:
from lib2to3.pgen2.token import BACKQUOTE
import numbers
from random import shuffle
from xml.sax.handler import feature_external_ges
%matplotlib inline
import random
import torch

def synthetic_data(w,b,num_examples):
     x = torch.normal(0,1,(num_examples,len(w)))
     y = torch.matmul(x,w)+b
     y+= torch.normal(0,0.01,y.shape)
     return x,y.reshape((-1,1))

true_w  = torch.tensor([2,-3,4],dtype=torch.float)
true_b = 4.2
features,labels= synthetic_data(true_w,true_b,1000)

def data_iter(batch_size,features,labels):
    num_example =len(featrues)
    indices = list(range(num_example))
    random.shuffle(indices)
    for i in range(0,num_example,batch_size):
        batch_indices = torch.tensor(indices[i:min(i+batch_size,num_example)])

        yield features[batch_indices],labels[batch_indices]
batch_size=10 
for x, y in data_iter(batch_size,features,labels):
    print(x,'\n',y)
    break

tensor([[-0.3702, -0.5882, -0.2702],
        [ 1.5920, -0.5975,  0.6579],
        [ 0.1348, -1.3882, -0.3009],
        [-0.4006, -0.3580,  0.5757],
        [-1.3728,  0.4972, -0.3455],
        [ 0.1194, -0.3869, -0.1742],
        [ 0.6839,  0.4475,  0.1611],
        [-0.4269, -1.4057, -0.3914],
        [ 0.1179, -0.3094, -0.6969],
        [ 0.5021,  1.1965,  0.3941]]) 
 tensor([[ 4.1525],
        [11.8003],
        [ 7.4116],
        [ 6.7560],
        [-1.4304],
        [ 4.8947],
        [ 4.8626],
        [ 6.0043],
        [ 2.5552],
        [ 3.2080]])


In [66]:
import re


w = torch.normal(0,0.01,size=(2,1),requires_grad=True) #均值 方差 行2列1
b = torch.zeros(1,requires_grad=True)
def linreg(x,w,b):
    return torch.matmul(x,w)+b

def squared_loss(y_hat,y):
    return(y_hat-y.reshape(y_hat.shape))**2/2

def sgd(params,lr,batch_size):
    with torch.no_grad():
        for pararm in params:
            param -= lr *pararm.grad/batch_size
            param.grad.zero_()

lr = 0.03
num_epochs = 3
net =linreg
loss= squared_loss
for epoch in range(num_epochs):
    for x , y in data_iter(batch_size,features,labels):
        l = loss(net(x,w,b),y)
        l.sum().backward()
        sgd([w,b],lr,batch_size)
    with torch.no_grad():
        train_l = loss(net(features,w,b),labels)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (10x3 and 2x1)

In [2]:
from torch import nn
net = nn.Sequential(nn.Linear(2,1))
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)

e:\python\lib\site-packages\torch\nn\modules\linear.py:96: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))


tensor([0.])